# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('arena', models.IntegerField()),
                ('elixir_cost', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='royale')),
            ],
        ),
        migrations.CreateModel(
            name='Rarityy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='rarity_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rarity_cards', to='main.Rarityy'),
        ),
    ]
